/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: src/dds_generated/ControlMsg.h
  Source: /Users/jason/Documents/code/mujoco/mujoco_sim/src/dds/ControlMsg.idl
  Cyclone DDS: V0.10.5

*****************************************************************/
#ifndef DDSC_SRC_DDS_GENERATED_CONTROLMSG_H
#define DDSC_SRC_DDS_GENERATED_CONTROLMSG_H

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct MujocoDDS_ControlMsg
{
  uint32_t mode;
  uint32_t action;
  double values[16];
} MujocoDDS_ControlMsg;

extern const dds_topic_descriptor_t MujocoDDS_ControlMsg_desc;

#define MujocoDDS_ControlMsg__alloc() \
((MujocoDDS_ControlMsg*) dds_alloc (sizeof (MujocoDDS_ControlMsg)));

#define MujocoDDS_ControlMsg_free(d,o) \
dds_sample_free ((d), &MujocoDDS_ControlMsg_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_SRC_DDS_GENERATED_CONTROLMSG_H */
